library(foreign) 
library(dplyr)
library(tidyverse) 
library(rcompanion)
library(scales)
library(lubridate)
library(nycflights13)
library(zoo)
library(plyr)
library(Hmisc)
##Actual dataset
data1 <- read.csv("C:/Users/SALEM/Downloads/output.csv")  
View(data1)
describe(data1)
##counts of the variables in the datasets
data1 %>% count(County)
View(data1 %>% count(State))
View(data1 %>% count(Year))
View(data1 %>% count(Rate))
View(data1 %>% count(Month))

##Basic Visulations of data1
ggplot(data = data1) + stat_count(aes(x = Month))  + theme(axis.text.x = element_text(angle = 90)) 
ggplot(data = data1) + stat_count(aes(x = Year))  + theme(axis.text.x = element_text(angle = 90)) 
a = data1$Year
plotNormalHistogram(a)
b = data1$Rate
plotNormalHistogram(b)
##Massachusetts 
data2 <- filter(data1, State == "Massachusetts") 
View(data2)
summarise(data2, means = mean(Rate, na.rm = TRUE))
data4 <- arrange(data2, desc(Year)) 
View(data4)
ggplot(data = data4) + geom_histogram(mapping = aes(x = Rate), binwidth = 1)
x = data4$Rate
plotNormalHistogram(x)
ggplot(data = data4, mapping = aes(x = State, y = Rate)) + geom_boxplot() 
data3 <- filter(data2, Year == "2015") 
View(data3) 
summarise(data3, means = mean(Rate, na.rm = TRUE))
View(data3 %>% count(State, Rate))
averagerate <- group_by(data3, Month) 
data8 <- summarise(averagerate, means3 = mean(Rate, na.rm = TRUE))
View(data8)
graph <- data3 %>% group_by(State) %>% summarise(means4 = mean(Rate)) 
y = data3$Rate
plotNormalHistogram(y)
ggplot(data = data3, mapping = aes(x = State, y = Rate)) + geom_boxplot() 
data10 <- filter(data3, Month == "January") 
View(data10)
ggplot(data = data10) + geom_bar(mapping = aes(x = Rate, colour = Rate))
ggplot(data = data10, mapping = aes(x = State, y = Rate)) + geom_boxplot() 
View(data3 %>% count(County, Rate))
View(data11 <- filter(data2, State == "Massachusetts", County == "Middlesex County")) 
ggplot(data = data11, mapping = aes(x = State, y = Rate)) + geom_boxplot() 
grouping1 <- group_by(data11, Year,County)
view(summarise(grouping1, countymean = mean(Rate, na.rm = TRUE)))
View(data12 <- filter(data11, Year == "2015"))
ggplot(data = data12, mapping = aes(x = State, y = Rate)) + geom_boxplot() 
grouping2 <- group_by(data12, County, Year) 
View(summarise(grouping2, countymean2 = mean(Rate, na.rm = TRUE)))
c = data12$Rate
plotNormalHistogram(c)
d = data11$Rate
plotNormalHistogram(d)
View(data13 <- filter(data1, State == "Massachusetts", Year == "2015"))
ggplot(data = data13, mapping = aes(x = State, y = Rate)) + geom_boxplot() 
View(grouping3 <- group_by(data13,State,County )) 
View(summarise(grouping3, mean4 = mean(Rate, na.rm = TRUE)))


##New York
data5  <- filter(data1, State == "New York") 
ggplot(data = data5, mapping = aes(x = State, y = Rate)) + geom_boxplot() 

View(data5)
View(data5 %>% count(County))
summarise(data5, means2 = mean(Rate, na.rm = TRUE))
z = data5$Rate
plotNormalHistogram(z)
ggplot(data = data5) + geom_histogram(mapping = aes(x = Rate), binwidth = 1)
ggplot(data = data5) + geom_histogram(mapping = aes(x = Rate), binwidth = 1) + coord_cartesian(xlim = c(5,15))
View(data12)
month <- c("2", "10", "3", "8", "5", "1", "6", "9", "4", "12", "7", "11")
View(month)
day <- c("01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01")
View(day)
newvariable2 <- mutate(data12, month = month, day = day)
View(newvariable2)
newvariable3 <- newvariable2 %>% select(Year, month, day, County, Rate) %>% mutate(monthdate = make_date(Year, month, day))
sorting <- select(newvariable3, County:monthdate)
View(sorting)
sorting2 <- sorting %>% select(monthdate, Rate, County)
View(sorting2)
as.Date(sorting2$monthdate)
ggplot(sorting2, aes(x = monthdate, y = Rate, colour=County, group=County)) + geom_point(size=4) + geom_line(size=1.3) + scale_x_date(date_breaks = "months", date_labels = "%m/%d/%y") + theme(axis.text.x = element_text(angle = 100))

NewYork <- filter(data5, Year == "2001", County == "Suffolk County") 
View(NewYork)
newvariables <- mutate(NewYork, month = month, day = day)
View(newvariables)
nv2 <- newvariables %>% select(Year, month, day, County, Rate) %>% mutate(monthdate2 = make_date(Year, month, day))
View(nv2) 
sorting3 <- select(nv2, County:monthdate2)
View(sorting3)
as.Date(sorting3$monthdate2)
ggplot(sorting3, aes(x = monthdate2, y = Rate, colour=County, group=County)) + geom_point(size=4) + geom_line(size=1.3) + scale_x_date(date_breaks = "months", date_labels = "%m/%d/%y") + theme(axis.text.x = element_text(angle = 100))
MANY <- filter(data1,  State == "Massachusetts"| State == "New York")
ggplot(data = MANY, mapping = aes(x = State, y = Rate)) + geom_boxplot() 
View(MANY)
View(MANY2 <- filter(MANY, Year == "2001")) 
MANY3 <- filter(MANY2, County == "Suffolk"| County == "Suffolk County") 
View(MANY3)
ggplot(data = MANY3, mapping = aes(x = State, y = Rate)) + geom_boxplot() 
ggplot(data = MANY) + geom_histogram(mapping = aes(x = Rate), binwidth = 0.5) + coord_cartesian(ylim = c(0,50))
month2 <-  c("2", "2", "10", "10", "3", "3", "8", "8", "5", "5", "1", "1", "6", "6", "9", "9", "4", "4", "12", "12" ,"7", "7", "11", "11")
View(month2)
day2 <- c("01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01" )
View(day2)
month2 <-  c("2", "2", "10", "10", "3", "3", "8", "8", "5", "5", "1", "1", "6", "6", "9", "9", "4", "4", "12", "12" ,"7", "7", "11", "11")
View(month2)
day2 <- c("01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01" )
View(day2)
new <-  mutate(MANY3, month2 = month2, day2 = day2)
View(new)
nv3 <- new %>% select(Year, month2, day2, State, County, Rate) %>% mutate(monthdate3 = make_date(Year, month2, day2))
View(nv3)
sorting4 <- select(nv3, State:monthdate3)
View(sorting4) 
sorting5 <- sorting4 %>% select(monthdate3, Rate, State, County)
View(sorting5)
as.Date(sorting5$monthdate3)
ggplot(sorting5, aes(x = monthdate3, y = Rate, colour=State, group=State)) + geom_point(size=4) + geom_line(size=1.3) + scale_x_date(date_breaks = "months", date_labels = "%m/%d/%y") + theme(axis.text.x = element_text(angle = 100))
MANY5 <- filter(MANY, Year == "2001")
View(MANY5)
ggplot(data = MANY5, mapping = aes(x = State, y = Rate)) + geom_boxplot() 

#Filtering data for new england states
filter1 <- filter(data1, State == "Massachusetts" | State == "Rhode Island" | State == "Connecticut" | State == "Vermont" | State == "Maine" | State == "New Hampshire")
View(filter1) 
summarise(filter1, rateaverage = mean(Rate, na.rm = TRUE)) #Average of unemployment rate for the entire dataset
rateaveragebyyear <- group_by(filter1, Month, State) #Grouping by year
summarise(rateaveragebyyear, rateaverage2 = mean(Rate, na.rm = TRUE)) #Average of the unemployment rate in the dataset
ggplot(data = filter1) + stat_count(aes(x = Year))  + theme(axis.text.x = element_text(angle = 90)) #Observations that occured at each x value
View(filter1 %>% dplyr::count(Rate)) #Counting up how many of the Rates are in the dataset
r = filter1$Rate #Dealing mainly with the rate column
plotNormalHistogram(r) #Histogram showing how frequent the rates are in the dataset
filter2 <- filter(filter1, Year == "2015") #Filtering to only show the rows that have the year column at 2015
View(filter2)
summarise(filter2, rateaverage3 = mean(Rate, na.rm = TRUE)) #Average of the unemployment rate of the dataset in the year of 2015
ggplot(data = filter2) + geom_histogram(mapping = aes(x = Rate), binwidth = 0.5) + coord_cartesian(xlim = c(1,10)) #Histogram showing how frequent the rates are in the dataset
k = filter2$Rate
plotNormalHistogram(k) #Histogram showing how frequent the rates are
filter3 <- select(filter1, Year:State, Rate)
View(filter3)
View(filter3 %>% group_by(State, Year) %>% summarise(meanrate = mean(Rate, na.rm = TRUE)))
data1 %>% count(Rate)
ggplot(data = filter3, mapping = aes(x = State, y = Rate)) + geom_boxplot() 
p = filter1$Rate
plotNormalHistogram(p)


year2001 <- filter(data1, Year == "2001", State == "New York" | State == "Massachusetts")
View(year2001)
ggplot(data = year2001, mapping = aes(x = State, y = Rate)) + geom_boxplot() 
b = year2001$Rate
plotNormalHistogram(b)

nineteenhundreds <-  filter(data1, Year >= 1990 & Year <= 1991)
View(nineteenhundreds)
n1 = nineteenhundreds$Rate
plotNormalHistogram(n1)
boxplot(Rate~Year, data=nineteenhundreds, main = "Unemployment Rate during the recession", xlab = "Unemployment Rate", ylab = "Year", varwidth = TRUE, horizontal = TRUE)
ggplot(data = nineteenhundreds, mapping = aes(x = Year, y = Rate, group= Year)) + geom_boxplot() 
nineteenhundreds2 <- filter(data1, Year >= 1990 & Year <= 1999)
ggplot(data = nineteenhundreds2, mapping = aes(x = Year, y = Rate, group= Year)) + coord_cartesian(xlim = c(1990, 1999)) + geom_boxplot()
n2 = nineteenhundreds2$Rate
plotNormalHistogram(n2)
ggplot(data = nineteenhundreds2) + geom_histogram(mapping = aes(x = Rate), binwidth = 1) + coord_cartesian(xlim = c(0,10))

recession1 <- filter(MANY, Year == "2007" | Year == "2008" | Year == "2009")
View(recession1)
View(recession1 %>% dplyr::count(Rate))
ggplot(data = recession1, mapping = aes(x = State, y = Rate)) + geom_boxplot() 
ggplot(data = recession1, mapping = aes(x = Year, y = Rate, group = Year)) + geom_boxplot() 
recession2 <- filter(MANY, Year == 2007)
View(recession2)
ggplot(data = recession2, mapping = aes(x = State, y = Rate)) + geom_boxplot() 
recession3 <- filter(MANY, Year == 2008)
View(recession3)
ggplot(data = recession3, mapping = aes(x = State, y = Rate)) + geom_boxplot() 
recession4 <- filter(MANY, Year == 2009)
View(recession4)
ggplot(data = recession4, mapping = aes(x = Year, y = Rate, group = Year)) + geom_boxplot() 
by_county <-  group_by(recession4, Year)
summarise(by_county, mean = mean(Rate, na.rm = TRUE))
recession4 %>% count(Rate)
View(recession4 %>% dplyr::count(Rate))
recession4 %>% dplyr::count(ggplot2::cut_width(Rate, 5))
suffolk1 <- filter(recession2, County == "Middlesex County"| County == "New York County")
View(suffolk1)
ggplot(data = suffolk1, mapping = aes(x = County, y = Rate)) + geom_boxplot() 
boxplot(Rate~Year, data=recession1, main = "Unemployment Rate during the recession", xlab = "Unemployment Rate", ylab = "Year", varwidth = TRUE, horizontal = TRUE)
ggplot(data = year2001, mapping = aes(x = State, y = Rate), col = rainbow(length(unique(year2001$State)))) + geom_boxplot() 
ggplot(data = year2001, mapping = aes(x = State, y = Rate)) + geom_boxplot() 
ggplot(data = recession1) + geom_point(mapping = aes(x = Year, y = Rate)) + coord_cartesian(ylim = c(1,5))
recession1 %>% count(cut_width(Rate,5))
recession2 %>% count(cut_width(Rate,5))
recession3 %>% count(cut_width(Rate,5))
recession4 %>% count(cut_width(Rate,5))
a = recession1$Rate
plotNormalHistogram(a)
b = recession2$Rate
plotNormalHistogram(b)
c = recession3$Rate
plotNormalHistogram(c)
d = recession4$Rate
plotNormalHistogram(d)

#chisquare tests
attach(data1)
chisq.test(table(Rate))
chisq.test(table(State))
chisq.test(table(County))
chisq.test(table(Year))
chisq.test(State, Rate)
chisq.test(Rate, Year)
chisq.test(County, Rate)


attach(data2)
chisq.test(table(Rate))
chisq.test(table(County))
chisq.test(table(Year))
chisq.test(Rate, Year)
chisq.test(County, Rate)


attach(data5)
chisq.test(table(Rate))
chisq.test(table(County))
chisq.test(table(Year))
chisq.test(Rate, Year)
chisq.test(County, Rate)

attach(filter1)
chisq.test(table(Rate))
chisq.test(table(County))
chisq.test(table(State))
chisq.test(Rate, Year)
chisq.test(County, Rate)
chisq.test(State, County)

attach(recession1)
chisq.test(table(Rate)) 
chisq.test(table(State))
chisq.test(table(County))
chisq.test(State, Rate)
chisq.test(County, Rate)

attach(recession2)
chisq.test(table(Rate))
chisq.test(table(State))
chisq.test(table(County))
chisq.test(State, County)
chisq.test(State, Rate)
chisq.test(County, Rate)

attach(recession3)
chisq.test(table(Rate))
chisq.test(table(State))
chisq.test(table(County))
chisq.test(State, Rate)
chisq.test(County, Rate)

attach(recession4)
chisq.test(table(Rate)) 
chisq.test(table(State)) 
chisq.test(table(County))
chisq.test(State, Rate)
chisq.test(County, Rate)
chisq.test(Month, Rate)
recession1 %>% dplyr::count(ggplot2::cut_width(Rate, 5))
recession2 %>% dplyr::count(ggplot2::cut_width(Rate, 5))
recession3 %>% dplyr::count(ggplot2::cut_width(Rate, 5))
recession4 %>% dplyr::count(ggplot2::cut_width(Rate, 5))

